apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rememberme-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:YJunSuk/devops-k8s-manifests.git
    targetRevision: main
    path: rememberme-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: rememberme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
